/*
 * File:           C:\Users\Vincent\Desktop\MyDSPI_20170413\SS_MyDSPi_V122\SS_MyDSPi_V122_IC_1_PARAM.h
 *
 * Created:        Monday, June 12, 2017 11:32:11 AM
 * Description:    SS_MyDSPi_V122:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2017 Analog Devices, Inc. All rights reserved.
 */
#ifndef __SS_MYDSPI_V122_IC_1_PARAM_H__
#define __SS_MYDSPI_V122_IC_1_PARAM_H__


/* Module Tone1 - Sine Tone*/
#define MOD_TONE1_COUNT                                3
#define MOD_TONE1_DEVICE                               "IC1"
#define MOD_STATIC_TONE1_ALG0_MASK_ADDR                0
#define MOD_STATIC_TONE1_ALG0_MASK_FIXPT               0x000000FF
#define MOD_STATIC_TONE1_ALG0_MASK_VALUE               SIGMASTUDIOTYPE_INTEGER_CONVERT(255)
#define MOD_STATIC_TONE1_ALG0_MASK_TYPE                SIGMASTUDIOTYPE_INTEGER
#define MOD_TONE1_ALG0_INCREMENT_ADDR                  1
#define MOD_TONE1_ALG0_INCREMENT_FIXPT                 0x0002AAAE
#define MOD_TONE1_ALG0_INCREMENT_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.02083375)
#define MOD_TONE1_ALG0_INCREMENT_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_TONE1_ALG0_ON_ADDR                         2
#define MOD_TONE1_ALG0_ON_FIXPT                        0x00800000
#define MOD_TONE1_ALG0_ON_VALUE                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_TONE1_ALG0_ON_TYPE                         SIGMASTUDIOTYPE_FIXPOINT

/* Module Tone1_2 - Sine Tone*/
#define MOD_TONE1_2_COUNT                              3
#define MOD_TONE1_2_DEVICE                             "IC1"
#define MOD_STATIC_TONE1_2_ALG0_MASK_ADDR              3
#define MOD_STATIC_TONE1_2_ALG0_MASK_FIXPT             0x000000FF
#define MOD_STATIC_TONE1_2_ALG0_MASK_VALUE             SIGMASTUDIOTYPE_INTEGER_CONVERT(255)
#define MOD_STATIC_TONE1_2_ALG0_MASK_TYPE              SIGMASTUDIOTYPE_INTEGER
#define MOD_TONE1_2_ALG0_INCREMENT_ADDR                4
#define MOD_TONE1_2_ALG0_INCREMENT_FIXPT               0x001AAAAE
#define MOD_TONE1_2_ALG0_INCREMENT_VALUE               SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.20833375)
#define MOD_TONE1_2_ALG0_INCREMENT_TYPE                SIGMASTUDIOTYPE_FIXPOINT
#define MOD_TONE1_2_ALG0_ON_ADDR                       5
#define MOD_TONE1_2_ALG0_ON_FIXPT                      0x00800000
#define MOD_TONE1_2_ALG0_ON_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_TONE1_2_ALG0_ON_TYPE                       SIGMASTUDIOTYPE_FIXPOINT

/* Module Channel_20_Merger_2 - Signal Merger*/
#define MOD_CHANNEL_20_MERGER_2_COUNT                  1
#define MOD_CHANNEL_20_MERGER_2_DEVICE                 "IC1"
#define MOD_CHANNEL_20_MERGER_2_SINGLECTRLMIXER19401_ADDR 6
#define MOD_CHANNEL_20_MERGER_2_SINGLECTRLMIXER19401_FIXPT 0x00400000
#define MOD_CHANNEL_20_MERGER_2_SINGLECTRLMIXER19401_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.5)
#define MOD_CHANNEL_20_MERGER_2_SINGLECTRLMIXER19401_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Signal_Selector_20 - Stereo Switch Nx2*/
#define MOD_SIGNAL_SELECTOR_20_COUNT                   3
#define MOD_SIGNAL_SELECTOR_20_DEVICE                  "IC1"
#define MOD_SIGNAL_SELECTOR_20_ALG0_STAGE0_STEREOSWITCHNOSLEW_ADDR 7
#define MOD_SIGNAL_SELECTOR_20_ALG0_STAGE0_STEREOSWITCHNOSLEW_FIXPT 0x00800000
#define MOD_SIGNAL_SELECTOR_20_ALG0_STAGE0_STEREOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SIGNAL_SELECTOR_20_ALG0_STAGE0_STEREOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SIGNAL_SELECTOR_20_ALG0_STAGE1_STEREOSWITCHNOSLEW_ADDR 8
#define MOD_SIGNAL_SELECTOR_20_ALG0_STAGE1_STEREOSWITCHNOSLEW_FIXPT 0x00000000
#define MOD_SIGNAL_SELECTOR_20_ALG0_STAGE1_STEREOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_SIGNAL_SELECTOR_20_ALG0_STAGE1_STEREOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SIGNAL_SELECTOR_20_ALG0_STAGE2_STEREOSWITCHNOSLEW_ADDR 9
#define MOD_SIGNAL_SELECTOR_20_ALG0_STAGE2_STEREOSWITCHNOSLEW_FIXPT 0x00000000
#define MOD_SIGNAL_SELECTOR_20_ALG0_STAGE2_STEREOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_SIGNAL_SELECTOR_20_ALG0_STAGE2_STEREOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Mute L - Mute*/
#define MOD_MUTEL_COUNT                                1
#define MOD_MUTEL_DEVICE                               "IC1"
#define MOD_MUTEL_MUTENOSLEWALG6MUTE_ADDR              10
#define MOD_MUTEL_MUTENOSLEWALG6MUTE_FIXPT             0x00800000
#define MOD_MUTEL_MUTENOSLEWALG6MUTE_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MUTEL_MUTENOSLEWALG6MUTE_TYPE              SIGMASTUDIOTYPE_FIXPOINT

/* Module Mute R - Mute*/
#define MOD_MUTER_COUNT                                1
#define MOD_MUTER_DEVICE                               "IC1"
#define MOD_MUTER_MUTENOSLEWALG7MUTE_ADDR              11
#define MOD_MUTER_MUTENOSLEWALG7MUTE_FIXPT             0x00800000
#define MOD_MUTER_MUTENOSLEWALG7MUTE_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MUTER_MUTENOSLEWALG7MUTE_TYPE              SIGMASTUDIOTYPE_FIXPOINT

/* Module Channel_20_Merger - Signal Merger*/
#define MOD_CHANNEL_20_MERGER_COUNT                    1
#define MOD_CHANNEL_20_MERGER_DEVICE                   "IC1"
#define MOD_CHANNEL_20_MERGER_SINGLECTRLMIXER19402_ADDR 12
#define MOD_CHANNEL_20_MERGER_SINGLECTRLMIXER19402_FIXPT 0x00400000
#define MOD_CHANNEL_20_MERGER_SINGLECTRLMIXER19402_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.5)
#define MOD_CHANNEL_20_MERGER_SINGLECTRLMIXER19402_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Master_20_Volume - Single Volume*/
#define MOD_MASTER_20_VOLUME_COUNT                     1
#define MOD_MASTER_20_VOLUME_DEVICE                    "IC1"
#define MOD_MASTER_20_VOLUME_GAIN1940ALGNS1_ADDR       13
#define MOD_MASTER_20_VOLUME_GAIN1940ALGNS1_FIXPT      0x000CCCCC
#define MOD_MASTER_20_VOLUME_GAIN1940ALGNS1_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.1)
#define MOD_MASTER_20_VOLUME_GAIN1940ALGNS1_TYPE       SIGMASTUDIOTYPE_FIXPOINT

/* Module EQ - General (2nd order)*/
#define MOD_EQ_COUNT                                   5
#define MOD_EQ_DEVICE                                  "IC1"
#define MOD_EQ_ALG0_STAGE0_B0_ADDR                     14
#define MOD_EQ_ALG0_STAGE0_B0_FIXPT                    0x00800000
#define MOD_EQ_ALG0_STAGE0_B0_VALUE                    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_EQ_ALG0_STAGE0_B0_TYPE                     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_ALG0_STAGE0_B1_ADDR                     15
#define MOD_EQ_ALG0_STAGE0_B1_FIXPT                    0x00000000
#define MOD_EQ_ALG0_STAGE0_B1_VALUE                    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_ALG0_STAGE0_B1_TYPE                     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_ALG0_STAGE0_B2_ADDR                     16
#define MOD_EQ_ALG0_STAGE0_B2_FIXPT                    0x00000000
#define MOD_EQ_ALG0_STAGE0_B2_VALUE                    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_ALG0_STAGE0_B2_TYPE                     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_ALG0_STAGE0_A1_ADDR                     17
#define MOD_EQ_ALG0_STAGE0_A1_FIXPT                    0x00000000
#define MOD_EQ_ALG0_STAGE0_A1_VALUE                    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_ALG0_STAGE0_A1_TYPE                     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_ALG0_STAGE0_A2_ADDR                     18
#define MOD_EQ_ALG0_STAGE0_A2_FIXPT                    0x00000000
#define MOD_EQ_ALG0_STAGE0_A2_VALUE                    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_ALG0_STAGE0_A2_TYPE                     SIGMASTUDIOTYPE_FIXPOINT

/* Module EQ_2 - General (2nd order)*/
#define MOD_EQ_2_COUNT                                 5
#define MOD_EQ_2_DEVICE                                "IC1"
#define MOD_EQ_2_ALG0_STAGE0_B0_ADDR                   19
#define MOD_EQ_2_ALG0_STAGE0_B0_FIXPT                  0x00800000
#define MOD_EQ_2_ALG0_STAGE0_B0_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_EQ_2_ALG0_STAGE0_B0_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_2_ALG0_STAGE0_B1_ADDR                   20
#define MOD_EQ_2_ALG0_STAGE0_B1_FIXPT                  0x00000000
#define MOD_EQ_2_ALG0_STAGE0_B1_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_2_ALG0_STAGE0_B1_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_2_ALG0_STAGE0_B2_ADDR                   21
#define MOD_EQ_2_ALG0_STAGE0_B2_FIXPT                  0x00000000
#define MOD_EQ_2_ALG0_STAGE0_B2_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_2_ALG0_STAGE0_B2_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_2_ALG0_STAGE0_A1_ADDR                   22
#define MOD_EQ_2_ALG0_STAGE0_A1_FIXPT                  0x00000000
#define MOD_EQ_2_ALG0_STAGE0_A1_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_2_ALG0_STAGE0_A1_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_2_ALG0_STAGE0_A2_ADDR                   23
#define MOD_EQ_2_ALG0_STAGE0_A2_FIXPT                  0x00000000
#define MOD_EQ_2_ALG0_STAGE0_A2_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_2_ALG0_STAGE0_A2_TYPE                   SIGMASTUDIOTYPE_FIXPOINT

/* Module EQ_3 - General (2nd order)*/
#define MOD_EQ_3_COUNT                                 5
#define MOD_EQ_3_DEVICE                                "IC1"
#define MOD_EQ_3_ALG0_STAGE0_B0_ADDR                   24
#define MOD_EQ_3_ALG0_STAGE0_B0_FIXPT                  0x00800000
#define MOD_EQ_3_ALG0_STAGE0_B0_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_EQ_3_ALG0_STAGE0_B0_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_3_ALG0_STAGE0_B1_ADDR                   25
#define MOD_EQ_3_ALG0_STAGE0_B1_FIXPT                  0x00000000
#define MOD_EQ_3_ALG0_STAGE0_B1_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_3_ALG0_STAGE0_B1_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_3_ALG0_STAGE0_B2_ADDR                   26
#define MOD_EQ_3_ALG0_STAGE0_B2_FIXPT                  0x00000000
#define MOD_EQ_3_ALG0_STAGE0_B2_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_3_ALG0_STAGE0_B2_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_3_ALG0_STAGE0_A1_ADDR                   27
#define MOD_EQ_3_ALG0_STAGE0_A1_FIXPT                  0x00000000
#define MOD_EQ_3_ALG0_STAGE0_A1_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_3_ALG0_STAGE0_A1_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_3_ALG0_STAGE0_A2_ADDR                   28
#define MOD_EQ_3_ALG0_STAGE0_A2_FIXPT                  0x00000000
#define MOD_EQ_3_ALG0_STAGE0_A2_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_3_ALG0_STAGE0_A2_TYPE                   SIGMASTUDIOTYPE_FIXPOINT

/* Module EQ_4 - General (2nd order)*/
#define MOD_EQ_4_COUNT                                 5
#define MOD_EQ_4_DEVICE                                "IC1"
#define MOD_EQ_4_ALG0_STAGE0_B0_ADDR                   29
#define MOD_EQ_4_ALG0_STAGE0_B0_FIXPT                  0x00800000
#define MOD_EQ_4_ALG0_STAGE0_B0_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_EQ_4_ALG0_STAGE0_B0_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_4_ALG0_STAGE0_B1_ADDR                   30
#define MOD_EQ_4_ALG0_STAGE0_B1_FIXPT                  0x00000000
#define MOD_EQ_4_ALG0_STAGE0_B1_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_4_ALG0_STAGE0_B1_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_4_ALG0_STAGE0_B2_ADDR                   31
#define MOD_EQ_4_ALG0_STAGE0_B2_FIXPT                  0x00000000
#define MOD_EQ_4_ALG0_STAGE0_B2_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_4_ALG0_STAGE0_B2_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_4_ALG0_STAGE0_A1_ADDR                   32
#define MOD_EQ_4_ALG0_STAGE0_A1_FIXPT                  0x00000000
#define MOD_EQ_4_ALG0_STAGE0_A1_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_4_ALG0_STAGE0_A1_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_4_ALG0_STAGE0_A2_ADDR                   33
#define MOD_EQ_4_ALG0_STAGE0_A2_FIXPT                  0x00000000
#define MOD_EQ_4_ALG0_STAGE0_A2_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_4_ALG0_STAGE0_A2_TYPE                   SIGMASTUDIOTYPE_FIXPOINT

/* Module EQ_5 - General (2nd order)*/
#define MOD_EQ_5_COUNT                                 5
#define MOD_EQ_5_DEVICE                                "IC1"
#define MOD_EQ_5_ALG0_STAGE0_B0_ADDR                   34
#define MOD_EQ_5_ALG0_STAGE0_B0_FIXPT                  0x00800000
#define MOD_EQ_5_ALG0_STAGE0_B0_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_EQ_5_ALG0_STAGE0_B0_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_5_ALG0_STAGE0_B1_ADDR                   35
#define MOD_EQ_5_ALG0_STAGE0_B1_FIXPT                  0x00000000
#define MOD_EQ_5_ALG0_STAGE0_B1_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_5_ALG0_STAGE0_B1_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_5_ALG0_STAGE0_B2_ADDR                   36
#define MOD_EQ_5_ALG0_STAGE0_B2_FIXPT                  0x00000000
#define MOD_EQ_5_ALG0_STAGE0_B2_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_5_ALG0_STAGE0_B2_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_5_ALG0_STAGE0_A1_ADDR                   37
#define MOD_EQ_5_ALG0_STAGE0_A1_FIXPT                  0x00000000
#define MOD_EQ_5_ALG0_STAGE0_A1_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_5_ALG0_STAGE0_A1_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_5_ALG0_STAGE0_A2_ADDR                   38
#define MOD_EQ_5_ALG0_STAGE0_A2_FIXPT                  0x00000000
#define MOD_EQ_5_ALG0_STAGE0_A2_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_5_ALG0_STAGE0_A2_TYPE                   SIGMASTUDIOTYPE_FIXPOINT

/* Module EQ_6 - General (2nd order)*/
#define MOD_EQ_6_COUNT                                 5
#define MOD_EQ_6_DEVICE                                "IC1"
#define MOD_EQ_6_ALG0_STAGE0_B0_ADDR                   39
#define MOD_EQ_6_ALG0_STAGE0_B0_FIXPT                  0x00800000
#define MOD_EQ_6_ALG0_STAGE0_B0_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_EQ_6_ALG0_STAGE0_B0_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_6_ALG0_STAGE0_B1_ADDR                   40
#define MOD_EQ_6_ALG0_STAGE0_B1_FIXPT                  0x00000000
#define MOD_EQ_6_ALG0_STAGE0_B1_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_6_ALG0_STAGE0_B1_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_6_ALG0_STAGE0_B2_ADDR                   41
#define MOD_EQ_6_ALG0_STAGE0_B2_FIXPT                  0x00000000
#define MOD_EQ_6_ALG0_STAGE0_B2_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_6_ALG0_STAGE0_B2_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_6_ALG0_STAGE0_A1_ADDR                   42
#define MOD_EQ_6_ALG0_STAGE0_A1_FIXPT                  0x00000000
#define MOD_EQ_6_ALG0_STAGE0_A1_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_6_ALG0_STAGE0_A1_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_6_ALG0_STAGE0_A2_ADDR                   43
#define MOD_EQ_6_ALG0_STAGE0_A2_FIXPT                  0x00000000
#define MOD_EQ_6_ALG0_STAGE0_A2_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_6_ALG0_STAGE0_A2_TYPE                   SIGMASTUDIOTYPE_FIXPOINT

/* Module EQ_7 - General (2nd order)*/
#define MOD_EQ_7_COUNT                                 5
#define MOD_EQ_7_DEVICE                                "IC1"
#define MOD_EQ_7_ALG0_STAGE0_B0_ADDR                   44
#define MOD_EQ_7_ALG0_STAGE0_B0_FIXPT                  0x00800000
#define MOD_EQ_7_ALG0_STAGE0_B0_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_EQ_7_ALG0_STAGE0_B0_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_7_ALG0_STAGE0_B1_ADDR                   45
#define MOD_EQ_7_ALG0_STAGE0_B1_FIXPT                  0x00000000
#define MOD_EQ_7_ALG0_STAGE0_B1_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_7_ALG0_STAGE0_B1_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_7_ALG0_STAGE0_B2_ADDR                   46
#define MOD_EQ_7_ALG0_STAGE0_B2_FIXPT                  0x00000000
#define MOD_EQ_7_ALG0_STAGE0_B2_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_7_ALG0_STAGE0_B2_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_7_ALG0_STAGE0_A1_ADDR                   47
#define MOD_EQ_7_ALG0_STAGE0_A1_FIXPT                  0x00000000
#define MOD_EQ_7_ALG0_STAGE0_A1_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_7_ALG0_STAGE0_A1_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_7_ALG0_STAGE0_A2_ADDR                   48
#define MOD_EQ_7_ALG0_STAGE0_A2_FIXPT                  0x00000000
#define MOD_EQ_7_ALG0_STAGE0_A2_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_7_ALG0_STAGE0_A2_TYPE                   SIGMASTUDIOTYPE_FIXPOINT

/* Module EQ_8 - General (2nd order)*/
#define MOD_EQ_8_COUNT                                 5
#define MOD_EQ_8_DEVICE                                "IC1"
#define MOD_EQ_8_ALG0_STAGE0_B0_ADDR                   49
#define MOD_EQ_8_ALG0_STAGE0_B0_FIXPT                  0x00800000
#define MOD_EQ_8_ALG0_STAGE0_B0_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_EQ_8_ALG0_STAGE0_B0_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_8_ALG0_STAGE0_B1_ADDR                   50
#define MOD_EQ_8_ALG0_STAGE0_B1_FIXPT                  0x00000000
#define MOD_EQ_8_ALG0_STAGE0_B1_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_8_ALG0_STAGE0_B1_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_8_ALG0_STAGE0_B2_ADDR                   51
#define MOD_EQ_8_ALG0_STAGE0_B2_FIXPT                  0x00000000
#define MOD_EQ_8_ALG0_STAGE0_B2_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_8_ALG0_STAGE0_B2_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_8_ALG0_STAGE0_A1_ADDR                   52
#define MOD_EQ_8_ALG0_STAGE0_A1_FIXPT                  0x00000000
#define MOD_EQ_8_ALG0_STAGE0_A1_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_8_ALG0_STAGE0_A1_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_8_ALG0_STAGE0_A2_ADDR                   53
#define MOD_EQ_8_ALG0_STAGE0_A2_FIXPT                  0x00000000
#define MOD_EQ_8_ALG0_STAGE0_A2_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_8_ALG0_STAGE0_A2_TYPE                   SIGMASTUDIOTYPE_FIXPOINT

/* Module EQ_9 - General (2nd order)*/
#define MOD_EQ_9_COUNT                                 5
#define MOD_EQ_9_DEVICE                                "IC1"
#define MOD_EQ_9_ALG0_STAGE0_B0_ADDR                   54
#define MOD_EQ_9_ALG0_STAGE0_B0_FIXPT                  0x00800000
#define MOD_EQ_9_ALG0_STAGE0_B0_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_EQ_9_ALG0_STAGE0_B0_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_9_ALG0_STAGE0_B1_ADDR                   55
#define MOD_EQ_9_ALG0_STAGE0_B1_FIXPT                  0x00000000
#define MOD_EQ_9_ALG0_STAGE0_B1_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_9_ALG0_STAGE0_B1_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_9_ALG0_STAGE0_B2_ADDR                   56
#define MOD_EQ_9_ALG0_STAGE0_B2_FIXPT                  0x00000000
#define MOD_EQ_9_ALG0_STAGE0_B2_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_9_ALG0_STAGE0_B2_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_9_ALG0_STAGE0_A1_ADDR                   57
#define MOD_EQ_9_ALG0_STAGE0_A1_FIXPT                  0x00000000
#define MOD_EQ_9_ALG0_STAGE0_A1_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_9_ALG0_STAGE0_A1_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_9_ALG0_STAGE0_A2_ADDR                   58
#define MOD_EQ_9_ALG0_STAGE0_A2_FIXPT                  0x00000000
#define MOD_EQ_9_ALG0_STAGE0_A2_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_9_ALG0_STAGE0_A2_TYPE                   SIGMASTUDIOTYPE_FIXPOINT

/* Module EQ_10 - General (2nd order)*/
#define MOD_EQ_10_COUNT                                5
#define MOD_EQ_10_DEVICE                               "IC1"
#define MOD_EQ_10_ALG0_STAGE0_B0_ADDR                  59
#define MOD_EQ_10_ALG0_STAGE0_B0_FIXPT                 0x00800000
#define MOD_EQ_10_ALG0_STAGE0_B0_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_EQ_10_ALG0_STAGE0_B0_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_10_ALG0_STAGE0_B1_ADDR                  60
#define MOD_EQ_10_ALG0_STAGE0_B1_FIXPT                 0x00000000
#define MOD_EQ_10_ALG0_STAGE0_B1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_10_ALG0_STAGE0_B1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_10_ALG0_STAGE0_B2_ADDR                  61
#define MOD_EQ_10_ALG0_STAGE0_B2_FIXPT                 0x00000000
#define MOD_EQ_10_ALG0_STAGE0_B2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_10_ALG0_STAGE0_B2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_10_ALG0_STAGE0_A1_ADDR                  62
#define MOD_EQ_10_ALG0_STAGE0_A1_FIXPT                 0x00000000
#define MOD_EQ_10_ALG0_STAGE0_A1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_10_ALG0_STAGE0_A1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_10_ALG0_STAGE0_A2_ADDR                  63
#define MOD_EQ_10_ALG0_STAGE0_A2_FIXPT                 0x00000000
#define MOD_EQ_10_ALG0_STAGE0_A2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_10_ALG0_STAGE0_A2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT

/* Module EQ_11 - General (2nd order)*/
#define MOD_EQ_11_COUNT                                5
#define MOD_EQ_11_DEVICE                               "IC1"
#define MOD_EQ_11_ALG0_STAGE0_B0_ADDR                  64
#define MOD_EQ_11_ALG0_STAGE0_B0_FIXPT                 0x00800000
#define MOD_EQ_11_ALG0_STAGE0_B0_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_EQ_11_ALG0_STAGE0_B0_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_11_ALG0_STAGE0_B1_ADDR                  65
#define MOD_EQ_11_ALG0_STAGE0_B1_FIXPT                 0x00000000
#define MOD_EQ_11_ALG0_STAGE0_B1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_11_ALG0_STAGE0_B1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_11_ALG0_STAGE0_B2_ADDR                  66
#define MOD_EQ_11_ALG0_STAGE0_B2_FIXPT                 0x00000000
#define MOD_EQ_11_ALG0_STAGE0_B2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_11_ALG0_STAGE0_B2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_11_ALG0_STAGE0_A1_ADDR                  67
#define MOD_EQ_11_ALG0_STAGE0_A1_FIXPT                 0x00000000
#define MOD_EQ_11_ALG0_STAGE0_A1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_11_ALG0_STAGE0_A1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_11_ALG0_STAGE0_A2_ADDR                  68
#define MOD_EQ_11_ALG0_STAGE0_A2_FIXPT                 0x00000000
#define MOD_EQ_11_ALG0_STAGE0_A2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_11_ALG0_STAGE0_A2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT

/* Module EQ_12 - General (2nd order)*/
#define MOD_EQ_12_COUNT                                5
#define MOD_EQ_12_DEVICE                               "IC1"
#define MOD_EQ_12_ALG0_STAGE0_B0_ADDR                  69
#define MOD_EQ_12_ALG0_STAGE0_B0_FIXPT                 0x00800000
#define MOD_EQ_12_ALG0_STAGE0_B0_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_EQ_12_ALG0_STAGE0_B0_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_12_ALG0_STAGE0_B1_ADDR                  70
#define MOD_EQ_12_ALG0_STAGE0_B1_FIXPT                 0x00000000
#define MOD_EQ_12_ALG0_STAGE0_B1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_12_ALG0_STAGE0_B1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_12_ALG0_STAGE0_B2_ADDR                  71
#define MOD_EQ_12_ALG0_STAGE0_B2_FIXPT                 0x00000000
#define MOD_EQ_12_ALG0_STAGE0_B2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_12_ALG0_STAGE0_B2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_12_ALG0_STAGE0_A1_ADDR                  72
#define MOD_EQ_12_ALG0_STAGE0_A1_FIXPT                 0x00000000
#define MOD_EQ_12_ALG0_STAGE0_A1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_12_ALG0_STAGE0_A1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_12_ALG0_STAGE0_A2_ADDR                  73
#define MOD_EQ_12_ALG0_STAGE0_A2_FIXPT                 0x00000000
#define MOD_EQ_12_ALG0_STAGE0_A2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_12_ALG0_STAGE0_A2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT

/* Module EQ_13 - General (2nd order)*/
#define MOD_EQ_13_COUNT                                5
#define MOD_EQ_13_DEVICE                               "IC1"
#define MOD_EQ_13_ALG0_STAGE0_B0_ADDR                  74
#define MOD_EQ_13_ALG0_STAGE0_B0_FIXPT                 0x00800000
#define MOD_EQ_13_ALG0_STAGE0_B0_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_EQ_13_ALG0_STAGE0_B0_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_13_ALG0_STAGE0_B1_ADDR                  75
#define MOD_EQ_13_ALG0_STAGE0_B1_FIXPT                 0x00000000
#define MOD_EQ_13_ALG0_STAGE0_B1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_13_ALG0_STAGE0_B1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_13_ALG0_STAGE0_B2_ADDR                  76
#define MOD_EQ_13_ALG0_STAGE0_B2_FIXPT                 0x00000000
#define MOD_EQ_13_ALG0_STAGE0_B2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_13_ALG0_STAGE0_B2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_13_ALG0_STAGE0_A1_ADDR                  77
#define MOD_EQ_13_ALG0_STAGE0_A1_FIXPT                 0x00000000
#define MOD_EQ_13_ALG0_STAGE0_A1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_13_ALG0_STAGE0_A1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_13_ALG0_STAGE0_A2_ADDR                  78
#define MOD_EQ_13_ALG0_STAGE0_A2_FIXPT                 0x00000000
#define MOD_EQ_13_ALG0_STAGE0_A2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_13_ALG0_STAGE0_A2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT

/* Module EQ_14 - General (2nd order)*/
#define MOD_EQ_14_COUNT                                5
#define MOD_EQ_14_DEVICE                               "IC1"
#define MOD_EQ_14_ALG0_STAGE0_B0_ADDR                  79
#define MOD_EQ_14_ALG0_STAGE0_B0_FIXPT                 0x00800000
#define MOD_EQ_14_ALG0_STAGE0_B0_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_EQ_14_ALG0_STAGE0_B0_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_14_ALG0_STAGE0_B1_ADDR                  80
#define MOD_EQ_14_ALG0_STAGE0_B1_FIXPT                 0x00000000
#define MOD_EQ_14_ALG0_STAGE0_B1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_14_ALG0_STAGE0_B1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_14_ALG0_STAGE0_B2_ADDR                  81
#define MOD_EQ_14_ALG0_STAGE0_B2_FIXPT                 0x00000000
#define MOD_EQ_14_ALG0_STAGE0_B2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_14_ALG0_STAGE0_B2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_14_ALG0_STAGE0_A1_ADDR                  82
#define MOD_EQ_14_ALG0_STAGE0_A1_FIXPT                 0x00000000
#define MOD_EQ_14_ALG0_STAGE0_A1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_14_ALG0_STAGE0_A1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_14_ALG0_STAGE0_A2_ADDR                  83
#define MOD_EQ_14_ALG0_STAGE0_A2_FIXPT                 0x00000000
#define MOD_EQ_14_ALG0_STAGE0_A2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_14_ALG0_STAGE0_A2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT

/* Module EQ_15 - General (2nd order)*/
#define MOD_EQ_15_COUNT                                5
#define MOD_EQ_15_DEVICE                               "IC1"
#define MOD_EQ_15_ALG0_STAGE0_B0_ADDR                  84
#define MOD_EQ_15_ALG0_STAGE0_B0_FIXPT                 0x00800000
#define MOD_EQ_15_ALG0_STAGE0_B0_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_EQ_15_ALG0_STAGE0_B0_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_15_ALG0_STAGE0_B1_ADDR                  85
#define MOD_EQ_15_ALG0_STAGE0_B1_FIXPT                 0x00000000
#define MOD_EQ_15_ALG0_STAGE0_B1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_15_ALG0_STAGE0_B1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_15_ALG0_STAGE0_B2_ADDR                  86
#define MOD_EQ_15_ALG0_STAGE0_B2_FIXPT                 0x00000000
#define MOD_EQ_15_ALG0_STAGE0_B2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_15_ALG0_STAGE0_B2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_15_ALG0_STAGE0_A1_ADDR                  87
#define MOD_EQ_15_ALG0_STAGE0_A1_FIXPT                 0x00000000
#define MOD_EQ_15_ALG0_STAGE0_A1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_15_ALG0_STAGE0_A1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ_15_ALG0_STAGE0_A2_ADDR                  88
#define MOD_EQ_15_ALG0_STAGE0_A2_FIXPT                 0x00000000
#define MOD_EQ_15_ALG0_STAGE0_A2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ_15_ALG0_STAGE0_A2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT

/* Module Crossover_20 - Crossover*/
#define MOD_CROSSOVER_20_COUNT                         21
#define MOD_CROSSOVER_20_DEVICE                        "IC1"
#define MOD_CROSSOVER_20_ALG0_CROSSOVERFILTER2WAYALGDP2LOWINVERT_ADDR 89
#define MOD_CROSSOVER_20_ALG0_CROSSOVERFILTER2WAYALGDP2LOWINVERT_FIXPT 0x00800000
#define MOD_CROSSOVER_20_ALG0_CROSSOVERFILTER2WAYALGDP2LOWINVERT_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_CROSSOVER_20_ALG0_CROSSOVERFILTER2WAYALGDP2LOWINVERT_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMB0_ADDR   90
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMB0_FIXPT  0x0000FF40
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMB0_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0077896300074859)
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMB0_TYPE   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMB1_ADDR   91
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMB1_FIXPT  0x0001FE80
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMB1_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0155792600149718)
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMB1_TYPE   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMA1_ADDR   92
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMA1_FIXPT  0x00DE1D71
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMA1_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.73527354108993)
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMA1_TYPE   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMB2_ADDR   93
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMB2_FIXPT  0x0000FF40
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMB2_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0077896300074859)
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMB2_TYPE   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMA2_ADDR   94
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMA2_FIXPT  0xFF9DE58E
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMA2_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.766432061119875)
#define MOD_CROSSOVER_20_ALG0_LOW_FILT1_PARAMA2_TYPE   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMB0_ADDR   95
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMB0_FIXPT  0x0000FF40
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMB0_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0077896300074859)
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMB0_TYPE   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMB1_ADDR   96
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMB1_FIXPT  0x0001FE80
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMB1_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0155792600149718)
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMB1_TYPE   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMA1_ADDR   97
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMA1_FIXPT  0x00DE1D71
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMA1_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.73527354108993)
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMA1_TYPE   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMB2_ADDR   98
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMB2_FIXPT  0x0000FF40
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMB2_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0077896300074859)
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMB2_TYPE   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMA2_ADDR   99
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMA2_FIXPT  0xFF9DE58E
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMA2_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.766432061119875)
#define MOD_CROSSOVER_20_ALG0_LOW_FILT2_PARAMA2_TYPE   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMB0_ADDR  100
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMB0_FIXPT 0x006A46A8
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMB0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.830281327322638)
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMB0_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMB1_ADDR  101
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMB1_FIXPT 0xFF2B72AF
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMB1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.66056265464528)
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMB1_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMA1_ADDR  102
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMA1_FIXPT 0x00D0D68E
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.63154776077331)
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMA1_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMB2_ADDR  103
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMB2_FIXPT 0x006A46A8
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMB2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.830281327322638)
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMB2_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMA2_ADDR  104
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMA2_FIXPT 0xFFA7BBED
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMA2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.689577548517243)
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT1_PARAMA2_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMB0_ADDR  105
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMB0_FIXPT 0x006A46A8
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMB0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.830281327322638)
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMB0_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMB1_ADDR  106
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMB1_FIXPT 0xFF2B72AF
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMB1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.66056265464528)
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMB1_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMA1_ADDR  107
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMA1_FIXPT 0x00D0D68E
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.63154776077331)
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMA1_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMB2_ADDR  108
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMB2_FIXPT 0x006A46A8
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMB2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.830281327322638)
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMB2_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMA2_ADDR  109
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMA2_FIXPT 0xFFA7BBED
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMA2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.689577548517243)
#define MOD_CROSSOVER_20_ALG0_HIGH_FILT2_PARAMA2_TYPE  SIGMASTUDIOTYPE_FIXPOINT

/* Module Bass_20_SampleAligner - Delay*/
#define MOD_BASS_20_SAMPLEALIGNER_COUNT                1
#define MOD_BASS_20_SAMPLEALIGNER_DEVICE               "IC1"
#define MOD_BASS_20_SAMPLEALIGNER_DELAYAMT_ADDR        110
#define MOD_BASS_20_SAMPLEALIGNER_DELAYAMT_FIXPT       0x00000001
#define MOD_BASS_20_SAMPLEALIGNER_DELAYAMT_VALUE       SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_BASS_20_SAMPLEALIGNER_DELAYAMT_TYPE        SIGMASTUDIOTYPE_INTEGER

/* Module Treble_20_SampleAligner - Delay*/
#define MOD_TREBLE_20_SAMPLEALIGNER_COUNT              1
#define MOD_TREBLE_20_SAMPLEALIGNER_DEVICE             "IC1"
#define MOD_TREBLE_20_SAMPLEALIGNER_DELAYAMT_ADDR      111
#define MOD_TREBLE_20_SAMPLEALIGNER_DELAYAMT_FIXPT     0x00000001
#define MOD_TREBLE_20_SAMPLEALIGNER_DELAYAMT_VALUE     SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_TREBLE_20_SAMPLEALIGNER_DELAYAMT_TYPE      SIGMASTUDIOTYPE_INTEGER

/* Module Bass_20_Phase - Signal Invert*/
#define MOD_BASS_20_PHASE_COUNT                        1
#define MOD_BASS_20_PHASE_DEVICE                       "IC1"
#define MOD_BASS_20_PHASE_EQ1940INVERT2GAIN_ADDR       112
#define MOD_BASS_20_PHASE_EQ1940INVERT2GAIN_FIXPT      0x00800000
#define MOD_BASS_20_PHASE_EQ1940INVERT2GAIN_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_BASS_20_PHASE_EQ1940INVERT2GAIN_TYPE       SIGMASTUDIOTYPE_FIXPOINT

/* Module Treble_20_Phase - Signal Invert*/
#define MOD_TREBLE_20_PHASE_COUNT                      1
#define MOD_TREBLE_20_PHASE_DEVICE                     "IC1"
#define MOD_TREBLE_20_PHASE_EQ1940INVERT1GAIN_ADDR     113
#define MOD_TREBLE_20_PHASE_EQ1940INVERT1GAIN_FIXPT    0x00800000
#define MOD_TREBLE_20_PHASE_EQ1940INVERT1GAIN_VALUE    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_TREBLE_20_PHASE_EQ1940INVERT1GAIN_TYPE     SIGMASTUDIOTYPE_FIXPOINT

/* Module Treble_20_Mute - Mute*/
#define MOD_TREBLE_20_MUTE_COUNT                       1
#define MOD_TREBLE_20_MUTE_DEVICE                      "IC1"
#define MOD_TREBLE_20_MUTE_MUTENOSLEWALG11MUTE_ADDR    114
#define MOD_TREBLE_20_MUTE_MUTENOSLEWALG11MUTE_FIXPT   0x00800000
#define MOD_TREBLE_20_MUTE_MUTENOSLEWALG11MUTE_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_TREBLE_20_MUTE_MUTENOSLEWALG11MUTE_TYPE    SIGMASTUDIOTYPE_FIXPOINT

/* Module Bass_20_Mute - Mute*/
#define MOD_BASS_20_MUTE_COUNT                         1
#define MOD_BASS_20_MUTE_DEVICE                        "IC1"
#define MOD_BASS_20_MUTE_MUTENOSLEWALG3MUTE_ADDR       115
#define MOD_BASS_20_MUTE_MUTENOSLEWALG3MUTE_FIXPT      0x00800000
#define MOD_BASS_20_MUTE_MUTENOSLEWALG3MUTE_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_BASS_20_MUTE_MUTENOSLEWALG3MUTE_TYPE       SIGMASTUDIOTYPE_FIXPOINT

/* Module Bass_20_Volume - Single Volume*/
#define MOD_BASS_20_VOLUME_COUNT                       1
#define MOD_BASS_20_VOLUME_DEVICE                      "IC1"
#define MOD_BASS_20_VOLUME_GAIN1940ALGNS4_ADDR         116
#define MOD_BASS_20_VOLUME_GAIN1940ALGNS4_FIXPT        0x00800000
#define MOD_BASS_20_VOLUME_GAIN1940ALGNS4_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_BASS_20_VOLUME_GAIN1940ALGNS4_TYPE         SIGMASTUDIOTYPE_FIXPOINT

/* Module Treble_20_Volume - Single Volume*/
#define MOD_TREBLE_20_VOLUME_COUNT                     1
#define MOD_TREBLE_20_VOLUME_DEVICE                    "IC1"
#define MOD_TREBLE_20_VOLUME_GAIN1940ALGNS3_ADDR       117
#define MOD_TREBLE_20_VOLUME_GAIN1940ALGNS3_FIXPT      0x00800000
#define MOD_TREBLE_20_VOLUME_GAIN1940ALGNS3_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_TREBLE_20_VOLUME_GAIN1940ALGNS3_TYPE       SIGMASTUDIOTYPE_FIXPOINT

/* Module Channel_20_Merger_3 - Signal Merger*/
#define MOD_CHANNEL_20_MERGER_3_COUNT                  1
#define MOD_CHANNEL_20_MERGER_3_DEVICE                 "IC1"
#define MOD_CHANNEL_20_MERGER_3_SINGLECTRLMIXER19403_ADDR 118
#define MOD_CHANNEL_20_MERGER_3_SINGLECTRLMIXER19403_FIXPT 0x00400000
#define MOD_CHANNEL_20_MERGER_3_SINGLECTRLMIXER19403_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.5)
#define MOD_CHANNEL_20_MERGER_3_SINGLECTRLMIXER19403_TYPE SIGMASTUDIOTYPE_FIXPOINT

#endif
